  auto_start: False
  filter:
    include_entities:
## Lampen en schakelaars    
      - light.fibaro_system_fgd212_dimmer_2_level_2
      - light.looplamp_2 ## Huiskamer - Looplamp
      - light.wenzhou_tkb_control_system_unknown_type0003_id0008_level
      - switch.neo_coolcam_power_plug_12a_switch ## Huiskamer - Staanlamp     
      - switch.fibaro_system_fgs213_switch_switch_3
      - switch.switch
      - switch.nachtlamp_denise ## Slaapkamer - Nachtlamp Denise
      - light.achterlamp_2
      - switch.fibaro_system_fgs223_double_relay_switch_2
      - switch.draadlamp
      - switch.fibaro_system_fgs223_double_relay_switch
      - switch.fibaro_system_fgs213_switch_switch_7 ## Keuken - Verlichting
      
## Sensoren

      - binary_sensor.door_window_sensor_158d00020b5397  # Terrasdeur
      - binary_sensor.door_window_sensor_158d000232cca3   # Meterkastdeur
      - binary_sensor.motion_sensor_158d0001e53bda   # overloop 1e
      - binary_sensor.motion_sensor_158d0002234615   # Huiskamer
      - binary_sensor.door_window_sensor_158d0002bfeffc   # Schuurdeur
      - binary_sensor.motion_sensor_158d0002ec812d   # Kleedkamer
      - binary_sensor.motion_sensor_158d0002ecb407   # Washok
          