  auto_start: False
  filter:
    include_entities:
      - light.keuken
      - light.looplamp_2
      - light.wenzhou_tkb_control_system_unknown_type0003_id0008_level
      - light.staanlamp
      - light.fibaro_system_fgd212_dimmer_2_level_2
      - vacuum.xiaomi_vacuum_cleaner
      - light.kerstboom
      - light.grondlampen
      - light.achterlamp_2
      - light.draadlamp
      - switch.fibaro_system_fgs213_switch_switch_3
      - light.nachtlamp_denise
      - light.nachtlamp_remco
      - switch.tradfri_outlet_2
      - alarm_control_panel.alarm


      
      