  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://10.40.0.9:8123
    service_name: google_say
  - platform: amazon_polly
    aws_access_key_id: AKIAIVZPLMVKMXZ3TV7Q
    aws_secret_access_key: !secret AWS_SECRET_ACCESS_KEY