- alias: UPS Warn when on Battery
  initial_state: 'on'
  trigger:
   - platform: state
     entity_id: sensor.nut_ups_status
     from: 'Online'
     to: 'On Battery'
   - platform: state
     entity_id: sensor.patchkast_status
     from: 'Online'
     to: 'On Battery Battery Discharging'
   - platform: state
     entity_id: sensor.patchkast_status
     from: 'Online Battery Charging'
     to: 'On Battery Battery Discharging'
  action:
   - service: notify.ios_iphoneremco_xs
     data_template:
       title: "Stroomuitval"
       message: "{{ trigger.to_state.attributes.friendly_name }} is naar batterij , UPS is nu {{ states.sensor.nut_ups_battery_charge.state }} procent en {{ ( states('sensor.nut_ups_battery_runtime')|float / 60) | round(0)}} min resterend"